---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: demogods
spec:
  selector:
    matchLabels:
      app: demogods
  template:
    metadata:
      labels:
        app: demogods
    spec:
      containers:
      - name: demogods
        image: quay.io/frankgreco/demogods:407dc1bf7c6074103f87dba777be99aeb424c603
        ports:
        - containerPort: 8080
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m