---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: demogods
spec:
  selector:
    matchLabels:
      app: demogods
  template:
    metadata:
      labels:
        app: demogods
    spec:
      containers:
      - name: demogods
        image: quay.io/frankgreco/demogods:5ada9ae19b5fc29b91b21d5b66b83c3ae7497f5e
        ports:
        - containerPort: 8080
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m