---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogods
spec:
  selector:
    matchLabels:
      app: demogods
  template:
    metadata:
      labels:
        app: demogods
    spec:
      containers:
      - name: demogods
        image: quay.io/frankgreco/demogods:9cbd95696ddb89e83314d0a23e5cf5806eb46168
        ports:
        - containerPort: 8080
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m