---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogods
spec:
  selector:
    matchLabels:
      app: demogods
  template:
    metadata:
      labels:
        app: demogods
    spec:
      containers:
      - name: demogods
        image: quay.io/frankgreco/demogods:78d73c857b48323b9b7da770b39df6e179661ac2
        ports:
        - containerPort: 8080
        - containerPort: 9000
        resources:
          requests:
            cpu: 100m